import http from "node:http";
import { URL } from "node:url";

const PORT=Number(process.env.PORT||10000), SB=process.env.SUPABASE_URL, KEY=process.env.SUPABASE_ANON_KEY;
const ORIGINS=(process.env.CORS_ORIGINS||"").split(",").map(x=>x.trim()).filter(Boolean);
if(!SB||!KEY) throw new Error("SUPABASE_URL and SUPABASE_ANON_KEY are required");

async function sb(path,opts={},token){
  const h=new Headers(opts.headers||{}); h.set("apikey",KEY); h.set("content-type","application/json");
  if(token) h.set("authorization","Bearer "+token);
  const r=await fetch(SB+path,{...opts,headers:h}); const t=await r.text(); let d=null;
  try{d=t?JSON.parse(t):null}catch{d=t}
  if(!r.ok) throw new Error(d?.message||d?.error_description||d?.error||`Supabase HTTP ${r.status}`);
  return d;
}
const enc=encodeURIComponent;
function send(res,status,data){res.writeHead(status,{"content-type":"application/json; charset=utf-8","access-control-allow-origin":ORIGINS[0]||"*","access-control-allow-headers":"authorization,content-type","access-control-allow-methods":"GET,POST,PATCH,DELETE,OPTIONS"});if(status===204)return res.end();res.end(JSON.stringify(data));}
function read(req){return new Promise((ok,bad)=>{let s="";req.on("data",c=>s+=c);req.on("end",()=>{try{ok(s?JSON.parse(s):{})}catch(e){bad(e)}})})}
function tok(req){return (req.headers.authorization||"").replace(/^Bearer\s+/i,"")||null}
const statusOut={received:"pending",confirmed:"confirmed",preparing:"preparing",ready:"ready",out_for_delivery:"delivering",delivered:"delivered",cancelled:"cancelled",waiting_client_decision:"waiting_client_decision"};
const statusIn={pending:"received",confirmed:"confirmed",preparing:"preparing",ready:"ready",delivering:"out_for_delivery",delivered:"delivered",cancelled:"cancelled"};
async function myRestaurant(m){const ms=await sb("/rest/v1/restaurant_members?user_id=eq."+enc(m.id)+"&status=eq.active&select=restaurant_id,member_role&limit=1",{},m.token);if(!ms?.[0])return null;const rs=await sb("/rest/v1/restaurants?id=eq."+enc(ms[0].restaurant_id)+"&select=*&limit=1",{},m.token);return rs?.[0]||null}
async function categories(token){return await sb("/rest/v1/categories?is_active=eq.true&select=id,name",{},token)}
function mapRestaurant(r){return r?{id:r.id,name:r.name,type:r.type||"Restaurant",description:r.description,address:r.address_text||"",city:r.city,lat:null,lng:null,phone:r.phone||"",email:r.email,openingHours:"",imageUrl:null,status:r.status,rating:Number(r.rating_average||0),reviewCount:Number(r.rating_count||0),ownerId:null,createdAt:r.created_at}:null}
function mapDish(d,c){const cat=(c||[]).find(x=>x.id===d.category_id);return{id:d.id,restaurantId:d.restaurant_id,name:d.name,description:d.description,price:Number(d.price_fcfa),category:cat?.name||"Plat principal",imageUrl:d.image_path,available:d.is_available,hasPromotion:false,promotionPrice:null,createdAt:d.created_at}}
function mapOrder(o){return{id:o.id,clientId:o.customer_id,restaurantId:o.restaurant_id,restaurantName:o.restaurants?.name||"Restaurant",status:statusOut[o.status]||o.status,items:(o.order_items||[]).map(i=>({dishId:i.dish_id,dishName:i.dish_name_snapshot,quantity:Number(i.quantity),unitPrice:Number(i.unit_price_fcfa),totalPrice:Number(i.line_total_fcfa)})),deliveryAddress:o.delivery_address_snapshot?.address_text||o.delivery_address_snapshot?.address||"",deliveryCity:o.delivery_address_snapshot?.city||"",deliveryLat:null,deliveryLng:null,scheduledAt:null,subtotal:Number(o.subtotal_fcfa),deliveryFee:Number(o.delivery_fee_fcfa),discount:Number(o.discount_fcfa),total:Number(o.total_fcfa),paymentMethod:o.payments?.[0]?.method||"orange_money",paymentStatus:o.payment_status,loyaltyPointsUsed:0,loyaltyPointsEarned:0,notes:null,createdAt:o.created_at}}

async function me(req){const t=tok(req);if(!t)return null;const u=await sb("/auth/v1/user",{},t);const p=await sb("/rest/v1/profiles?id=eq."+enc(u.id)+"&select=*&limit=1",{},t);return p?.[0]?{id:u.id,role:p[0].role,profile:p[0],token:t}:null}
const synthetic=p=>p.replace(/[^0-9+]/g,"")+"@auth.mon-restaurant.local";

async function signInOrCreateAccount({email,phone,password,name,role}){
  try{
    const a=await sb("/auth/v1/token?grant_type=password",{method:"POST",body:JSON.stringify({email,password})});
    return a;
  }catch{
    const a=await sb("/auth/v1/signup",{method:"POST",body:JSON.stringify({email,password,data:{full_name:name,phone,role}})});
    if(!a?.access_token) throw new Error("Bootstrap account requires email confirmation: "+email);
    await sb("/rest/v1/profiles",{method:"POST",headers:{Prefer:"resolution=merge-duplicates"},body:JSON.stringify({id:a.user.id,full_name:name,phone,role,status:"active"})},a.access_token);
    return a;
  }
}

async function bootstrapAccounts(){
  const adminEmail=process.env.BOOTSTRAP_ADMIN_EMAIL, adminPhone=process.env.BOOTSTRAP_ADMIN_PHONE, adminPassword=process.env.BOOTSTRAP_ADMIN_PASSWORD;
  const restoEmail=process.env.BOOTSTRAP_RESTAURANT_EMAIL, restoPhone=process.env.BOOTSTRAP_RESTAURANT_PHONE, restoPassword=process.env.BOOTSTRAP_RESTAURANT_PASSWORD;
  if(!adminEmail||!adminPhone||!adminPassword||!restoEmail||!restoPhone||!restoPassword) return;
  try{
    const admin=await signInOrCreateAccount({email:adminEmail,phone:adminPhone,password:adminPassword,name:"MON RESTAURANT Administrateur",role:"restaurant_owner"});
    await sb("/rest/v1/profiles?id=eq."+enc(admin.user.id),{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({full_name:"MON RESTAURANT Administrateur",phone:adminPhone,role:"admin",status:"active"})},admin.access_token);

    const resto=await signInOrCreateAccount({email:restoEmail,phone:restoPhone,password:restoPassword,name:"MON RESTAURANT Restaurateur",role:"restaurant_owner"});
    const members=await sb("/rest/v1/restaurant_members?user_id=eq."+enc(resto.user.id)+"&status=eq.active&select=restaurant_id&limit=1",{},resto.access_token);
    let restaurantId=members?.[0]?.restaurant_id||null;
    if(!restaurantId){
      restaurantId=await sb("/rest/v1/rpc/create_restaurant",{method:"POST",body:JSON.stringify({
        p_name:"MON RESTAURANT — Démo",
        p_city:"Ouagadougou",
        p_description:"Restaurant de démonstration MON RESTAURANT",
        p_phone:restoPhone,
        p_email:restoEmail,
        p_address_text:"Ouagadougou",
        p_neighborhood:null,
        p_location:null,
        p_location_accuracy_m:null
      })},resto.access_token);
    }
    try{
      await sb("/rest/v1/rpc/change_restaurant_status",{method:"POST",body:JSON.stringify({p_restaurant_id:restaurantId,p_new_status:"approved",p_reason:"Compte de démonstration MON RESTAURANT"})},admin.access_token);
    }catch{}
    console.log("Bootstrap accounts ready:",adminEmail,restoEmail);
  }catch(e){ console.error("Bootstrap accounts skipped:",e?.message||e); }
}

async function route(req,res){
  if(req.method==="OPTIONS"){res.writeHead(204,{"access-control-allow-origin":ORIGINS[0]||"*","access-control-allow-headers":"authorization,content-type","access-control-allow-methods":"GET,POST,PATCH,OPTIONS"});return res.end();}
  const u=new URL(req.url,"http://localhost"), p=u.pathname;
  try{
    if((p==="/health"||p==="/api/healthz")&&req.method==="GET") return send(res,200,{status:"ok",ok:true,service:"mon-restaurant-api",database:"supabase"});
    if(p==="/api/auth/register"&&req.method==="POST"){const b=await read(req);if(typeof b.name!=="string"||typeof b.phone!=="string"||typeof b.password!=="string"||!["client","restaurant_owner"].includes(b.role))return send(res,400,{error:"Invalid registration payload"});const ex=await sb("/rest/v1/profiles?phone=eq."+enc(b.phone.trim())+"&select=id&limit=1");if(ex?.length)return send(res,409,{error:"Phone number already registered"});const a=await sb("/auth/v1/signup",{method:"POST",body:JSON.stringify({email:b.email?.trim()||synthetic(b.phone),password:b.password,data:{full_name:b.name.trim(),phone:b.phone.trim(),role:b.role}})});if(!a.access_token)return send(res,201,{requiresConfirmation:true,user:{id:a.user?.id,name:b.name,phone:b.phone,role:b.role}});await sb("/rest/v1/profiles",{method:"POST",headers:{Prefer:"resolution=merge-duplicates"},body:JSON.stringify({id:a.user.id,full_name:b.name.trim(),phone:b.phone.trim(),role:b.role,status:"active"})},a.access_token);return send(res,201,{token:a.access_token,user:{id:a.user.id,name:b.name,phone:b.phone,email:a.user.email,role:b.role,loyaltyPoints:0,createdAt:a.user.created_at}});}
    if(p==="/api/auth/login"&&req.method==="POST"){const b=await read(req),ps=await sb("/rest/v1/profiles?phone=eq."+enc((b.phone||"").trim())+"&select=*&limit=1");if(!ps?.[0])return send(res,401,{error:"Invalid credentials"});const a=await sb("/auth/v1/token?grant_type=password",{method:"POST",body:JSON.stringify({email:synthetic(b.phone.trim()),password:b.password})});return send(res,200,{token:a.access_token,user:{id:ps[0].id,name:ps[0].full_name,phone:ps[0].phone,email:a.user?.email,role:ps[0].role,loyaltyPoints:0,createdAt:ps[0].created_at}});}
    if(p==="/api/auth/me"){const m=await me(req);if(!m)return send(res,401,{error:"Authentication required"});return send(res,200,{id:m.id,name:m.profile.full_name,phone:m.profile.phone,email:null,role:m.role,loyaltyPoints:0,createdAt:m.profile.created_at});}
    if(p==="/api/restaurants"&&req.method==="GET"){const d=await sb("/rest/v1/restaurants?status=eq.approved&order=created_at.desc&select=*");return send(res,200,(d||[]).map(mapRestaurant));}
    if(p==="/api/restaurants/mine"&&req.method==="GET"){const m=await me(req);if(!m||m.role!=="restaurant_owner")return send(res,403,{error:"Restaurant access required"});const r=await myRestaurant(m);if(!r)return send(res,404,{error:"Restaurant not found"});const [d,c]=await Promise.all([sb("/rest/v1/dishes?restaurant_id=eq."+enc(r.id)+"&select=*&order=created_at",{},m.token),categories(m.token)]);return send(res,200,{...mapRestaurant(r),dishes:(d||[]).map(x=>mapDish(x,c))});}
    if(/^\/api\/restaurants\/[^/]+$/.test(p)&&req.method==="GET"){const id=p.split("/").pop(),rs=await sb("/rest/v1/restaurants?id=eq."+enc(id)+"&status=eq.approved&select=*&limit=1");if(!rs?.[0])return send(res,404,{error:"Restaurant not found"});const [d,c]=await Promise.all([sb("/rest/v1/dishes?restaurant_id=eq."+enc(id)+"&select=*&order=created_at"),categories()]);return send(res,200,{...mapRestaurant(rs[0]),dishes:(d||[]).map(x=>mapDish(x,c))});}
    if(p==="/api/restaurants"&&req.method==="POST"){const m=await me(req);if(!m||m.role!=="restaurant_owner")return send(res,403,{error:"Restaurant owner required"});const b=await read(req);const id=await sb("/rest/v1/rpc/create_restaurant",{method:"POST",body:JSON.stringify({p_name:b.name,p_city:b.city,p_description:b.description||null,p_phone:b.phone||null,p_email:b.email||null,p_address_text:b.address||null,p_neighborhood:b.neighborhood||null,p_location:null,p_location_accuracy_m:null})},m.token);const r=await sb("/rest/v1/restaurants?id=eq."+enc(id)+"&select=*&limit=1",{},m.token);return send(res,201,mapRestaurant(r?.[0]));}
    if(/^\/api\/restaurants\/[^/]+\/stats$/.test(p)&&req.method==="GET"){const m=await me(req);if(!m||!["restaurant_owner","admin"].includes(m.role))return send(res,403,{error:"Access denied"});const id=p.split("/")[3];const os=await sb("/rest/v1/orders?restaurant_id=eq."+enc(id)+"&select=id,status,total_fcfa,created_at",{},m.token);const a=os||[],d=a.filter(x=>x.status==="delivered"),today=new Date().toISOString().slice(0,10),t=a.filter(x=>String(x.created_at).startsWith(today));const r=await sb("/rest/v1/restaurants?id=eq."+enc(id)+"&select=rating_average&limit=1",{},m.token);return send(res,200,{totalOrders:a.length,completedOrders:d.length,totalRevenue:d.reduce((s,x)=>s+Number(x.total_fcfa||0),0),commissionOwed:0,averageRating:r?.[0]?.rating_average==null?null:Number(r[0].rating_average),todayOrders:t.length,todayRevenue:t.filter(x=>x.status==="delivered").reduce((s,x)=>s+Number(x.total_fcfa||0),0)});}
    if(/^\/api\/restaurants\/[^/]+\/dishes(?:\/[^/]+)?$/.test(p)){const parts=p.split("/"),rid=parts[3],did=parts[5];if(req.method==="GET"){const [d,c]=await Promise.all([sb("/rest/v1/dishes?restaurant_id=eq."+enc(rid)+"&select=*&order=created_at"),categories()]);return send(res,200,(d||[]).map(x=>mapDish(x,c)));}const m=await me(req);if(!m||m.role!=="restaurant_owner")return send(res,403,{error:"Restaurant owner required"});const mine=await myRestaurant(m);if(!mine||mine.id!==rid)return send(res,403,{error:"Restaurant access denied"});if(req.method==="POST"){const b=await read(req),c=await sb("/rest/v1/categories?name=eq."+enc(b.category||"")+"&select=id&limit=1",{},m.token),id=await sb("/rest/v1/rpc/create_dish",{method:"POST",body:JSON.stringify({p_restaurant_id:rid,p_category_id:c?.[0]?.id||null,p_name:b.name,p_description:b.description||null,p_price_fcfa:Math.round(Number(b.price||0)),p_image_path:b.imageUrl||""})},m.token),d=await sb("/rest/v1/dishes?id=eq."+enc(id)+"&select=*&limit=1",{},m.token);return send(res,201,mapDish(d?.[0],c));}if(req.method==="PATCH"){const b=await read(req),c=await sb("/rest/v1/categories?name=eq."+enc(b.category||"")+"&select=id&limit=1",{},m.token);await sb("/rest/v1/rpc/update_dish",{method:"POST",body:JSON.stringify({p_dish_id:did,p_category_id:c?.[0]?.id||null,p_name:b.name,p_description:b.description||null,p_price_fcfa:Math.round(Number(b.price||0)),p_image_path:b.imageUrl||"",p_is_available:b.available!==false})},m.token);const d=await sb("/rest/v1/dishes?id=eq."+enc(did)+"&select=*&limit=1",{},m.token);return send(res,200,mapDish(d?.[0],c));}if(req.method==="DELETE"){await sb("/rest/v1/rpc/delete_dish",{method:"POST",body:JSON.stringify({p_dish_id:did})},m.token);return send(res,204);}}
    if(/^\/api\/restaurants\/[^/]+$/.test(p)&&req.method==="PATCH"){const m=await me(req);if(!m||m.role!=="restaurant_owner")return send(res,403,{error:"Restaurant owner required"});const id=p.split("/").pop(),r=await myRestaurant(m);if(!r||r.id!==id)return send(res,403,{error:"Restaurant access denied"});const b=await read(req);await sb("/rest/v1/rpc/update_my_restaurant",{method:"POST",body:JSON.stringify({p_restaurant_id:id,p_name:b.name||r.name,p_description:b.description??r.description,p_phone:b.phone??r.phone,p_email:b.email??r.email,p_address_text:b.address??r.address_text,p_city:b.city||r.city,p_neighborhood:b.neighborhood??r.neighborhood,p_location:null,p_location_accuracy_m:null,p_is_open:b.isOpen??r.is_open})},m.token);const n=await sb("/rest/v1/restaurants?id=eq."+enc(id)+"&select=*&limit=1",{},m.token);return send(res,200,mapRestaurant(n?.[0]));}
    if(p==="/api/orders"&&req.method==="GET"){const m=await me(req);if(!m)return send(res,401,{error:"Authentication required"});let q="?select=*,restaurants(name),order_items(*)&order=created_at.desc";if(m.role==="client")q+="&customer_id=eq."+enc(m.id);if(m.role==="restaurant_owner"){const r=await myRestaurant(m);if(!r)return send(res,200,[]);q+="&restaurant_id=eq."+enc(r.id);}return send(res,200,(await sb("/rest/v1/orders"+q,{},m.token)||[]).map(mapOrder));}
    if(p==="/api/orders"&&req.method==="POST"){const b=await read(req),t=tok(req);let cid=null;if(t){const a=await sb("/auth/v1/user",{},t);cid=a?.id||null}if(!cid&&(!b.guestName||!b.guestPhone))return send(res,400,{error:"Guest name and phone are required when not logged in"});const d=await sb("/rest/v1/rpc/create_order",{method:"POST",body:JSON.stringify({p_customer_id:cid,p_guest_name:b.guestName||null,p_guest_phone:b.guestPhone||null,p_restaurant_id:b.restaurantId,p_delivery_zone_id:b.deliveryZoneId||null,p_delivery_address_snapshot:{address_text:b.deliveryAddress,city:b.deliveryCity},p_delivery_location:null,p_items:(b.items||[]).map(i=>({dish_id:i.dishId,quantity:i.quantity})),p_payment_method:b.paymentMethod,p_idempotency_key:b.idempotencyKey||("v7-"+Date.now()),p_use_loyalty:b.useLoyaltyDiscount===true})},t);return send(res,201,Array.isArray(d)?d[0]:d);}
    if(p==="/api/delivery/quote"&&req.method==="GET"){const city=u.searchParams.get("city")||"",z=await sb("/rest/v1/delivery_zones?city=eq."+enc(city)+"&is_active=eq.true&order=base_fee_fcfa&limit=1"),fee=z?.[0]?.base_fee_fcfa||1000;return send(res,200,{fee,baseFee:fee,distanceKm:null,zoneId:z?.[0]?.id||null,currency:"FCFA",minimumFee:1000});}
    if(p==="/api/admin/stats"){const m=await me(req);if(!m||m.role!=="admin")return send(res,403,{error:"Admin access required"});const [us,rs,os]=await Promise.all([sb("/rest/v1/profiles?select=id,role",{},m.token),sb("/rest/v1/restaurants?select=id,status",{},m.token),sb("/rest/v1/orders?select=id,status,total_fcfa,created_at",{},m.token)]);const u=us||[],r=rs||[],o=os||[],today=new Date().toISOString().slice(0,10),byStatus={};o.forEach(x=>{const k=statusOut[x.status]||x.status;byStatus[k]=(byStatus[k]||0)+1});return send(res,200,{users:{total:u.length,clients:u.filter(x=>x.role==="client").length,restaurantOwners:u.filter(x=>x.role==="restaurant_owner").length,admins:u.filter(x=>x.role==="admin").length},restaurants:{total:r.length,pending:r.filter(x=>x.status==="pending").length,approved:r.filter(x=>x.status==="approved").length,suspended:r.filter(x=>x.status==="suspended").length},orders:{total:o.length,today:o.filter(x=>String(x.created_at).startsWith(today)).length,byStatus},revenue:{total:o.filter(x=>x.status==="delivered").reduce((s,x)=>s+Number(x.total_fcfa||0),0),today:o.filter(x=>x.status==="delivered"&&String(x.created_at).startsWith(today)).reduce((s,x)=>s+Number(x.total_fcfa||0),0),commission:0}});}
    if(p==="/api/admin/restaurants"&&req.method==="GET"){const m=await me(req);if(!m||m.role!=="admin")return send(res,403,{error:"Admin access required"});const rs=await sb("/rest/v1/restaurants?order=created_at.desc&select=*",{},m.token),out=[];for(const r of rs||[]){const mem=await sb("/rest/v1/restaurant_members?restaurant_id=eq."+enc(r.id)+"&member_role=eq.owner&select=user_id&limit=1",{},m.token),owner=mem?.[0]?(await sb("/rest/v1/profiles?id=eq."+enc(mem[0].user_id)+"&select=full_name,phone&limit=1",{},m.token))?.[0]:null;out.push({id:r.id,name:r.name,type:"Restaurant",city:r.city,phone:r.phone||"",email:r.email,status:r.status,rating:Number(r.rating_average||0),reviewCount:Number(r.rating_count||0),ownerId:mem?.[0]?.user_id||null,ownerName:owner?.full_name||null,ownerPhone:owner?.phone||null,createdAt:r.created_at});}return send(res,200,out);}
    if(/^\/api\/admin\/restaurants\/[^/]+\/status$/.test(p)&&req.method==="PATCH"){const m=await me(req);if(!m||m.role!=="admin")return send(res,403,{error:"Admin access required"});const id=p.split("/")[4],b=await read(req);if(!["pending","approved","suspended","rejected"].includes(b.status))return send(res,400,{error:"Invalid restaurant status"});const status=await sb("/rest/v1/rpc/change_restaurant_status",{method:"POST",body:JSON.stringify({p_restaurant_id:id,p_new_status:b.status,p_reason:null})},m.token);return send(res,200,{id,status});}
    if(p==="/api/admin/users"&&req.method==="GET"){const m=await me(req);if(!m||m.role!=="admin")return send(res,403,{error:"Admin access required"});const rows=await sb("/rest/v1/profiles?order=created_at.desc&select=id,full_name,phone,role,status,created_at",{},m.token),loy=await sb("/rest/v1/loyalty_accounts?select=user_id,points_balance",{},m.token),lm=new Map((loy||[]).map(x=>[x.user_id,Number(x.points_balance||0)]));return send(res,200,(rows||[]).map(x=>({id:x.id,name:x.full_name,phone:x.phone,email:null,role:x.role,loyaltyPoints:lm.get(x.id)||0,createdAt:x.created_at})));}
    if(/^\/api\/admin\/users\/[^/]+\/role$/.test(p)&&req.method==="PATCH"){const m=await me(req);if(!m||m.role!=="admin")return send(res,403,{error:"Admin access required"});const id=p.split("/")[4],b=await read(req);if(!["client","restaurant_owner","admin"].includes(b.role))return send(res,400,{error:"Invalid role"});const updated=await sb("/rest/v1/profiles?id=eq."+enc(id),{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({role:b.role})},m.token);return send(res,200,{id,role:updated?.[0]?.role||b.role});}
    if(p==="/api/admin/orders"&&req.method==="GET"){const m=await me(req);if(!m||m.role!=="admin")return send(res,403,{error:"Admin access required"});const rows=await sb("/rest/v1/orders?select=*,restaurants(name),order_items(id)&order=created_at.desc",{},m.token);return send(res,200,(rows||[]).map(o=>({id:o.id,customerId:o.customer_id,restaurantId:o.restaurant_id,restaurantName:o.restaurants?.name||"Restaurant",status:statusOut[o.status]||o.status,subtotal:Number(o.subtotal_fcfa),deliveryFee:Number(o.delivery_fee_fcfa),discount:Number(o.discount_fcfa),total:Number(o.total_fcfa),deliveryCity:o.delivery_address_snapshot?.city||"",paymentMethod:"orange_money",itemCount:(o.order_items||[]).length,createdAt:o.created_at})));}
    return send(res,404,{error:"Route not found"});
  }catch(e){return send(res,400,{error:e?.message||String(e)});}
}
http.createServer(route).listen(PORT,"0.0.0.0",()=>{console.log("MON-RESTAURANT API listening on "+PORT);bootstrapAccounts();});